"""Add downtime columns to operator_log

Revision ID: 5b915026a092
Revises: 
Create Date: 2025-06-12 13:06:41.677189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b915026a092'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('downtime_minutes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('downtime_category', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_log', schema=None) as batch_op:
        batch_op.drop_column('downtime_category')
        batch_op.drop_column('downtime_minutes')

    # ### end Alembic commands ### 